---
name: CI Pipeline
on:
  push:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yamllint
        run: sudo apt install -y yamllint

      - name: Check YAML files
        run: |
          yamllint .
