name: CI Pipeline
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Bash scripts
        run: |
          sudo apt install -y shellcheck
          shellcheck /usr/local/bin/cpu_monitor.sh